#!/usr/bin/env python3
"""Generate build.ninja for the canvas2d project.

Three build variants are produced from one source tree:

  release : -Os -fbounds-safety                       (the shipping build)
  debug   : -O0 -g -fbounds-safety -fsanitize=...       (address,integer,undefined)
  unsafe  : -Os                                         (same as release, minus
                                                         -fbounds-safety -- the
                                                         benchmark baseline)

`release` vs `unsafe` is an apples-to-apples measurement of what -fbounds-safety
costs: identical sources and optimisation, differing only in the bounds-safety
flag. `ninja benchcmp` runs hyperfine over the two.

The C core is compiled `-std=c23 -Werror -Weverything` (plus -fbounds-safety for
release/debug); only the handful of warnings below are disabled, each justified.

The Objective-C Metal shim (src/*.m) is the platform boundary. -fbounds-safety is
C-only and cannot apply to it; it is built -std=c23 with -Wall -Wextra, under the
sanitizers in debug. The shader is embedded with C23 #embed (--embed-dir=shaders)
and compiled at runtime; -MMD tracks the embed dependency.
"""

import os
import glob

HERE = os.path.dirname(os.path.abspath(__file__))


def rel(p):
    return os.path.relpath(p, HERE)


# --- flag groups -----------------------------------------------------------

CSTD = "-std=c23"
BOUNDS = "-fbounds-safety"

# Disabled warnings.  Keep this list short and justified.
CWARN_DISABLED = [
    # /usr/local/include sits on clang's default search path on this machine;
    # this is a cross-compilation hygiene warning, irrelevant to a native build.
    ("poison-system-directories", "spurious for a native (non-cross) build"),
    # We declare __counted_by locals at their point of use; C89-style
    # "declare everything up top" is antithetical to modern C23.
    ("declaration-after-statement", "we use C23 declare-at-use style"),
    # Struct tail padding is not a correctness signal for this code.
    ("padded", "padding is not a correctness concern here"),
    # We target C23; warning that C23 features are 'incompatible with older C'
    # is backwards for this project.
    ("pre-c23-compat", "we deliberately target C23"),
    # This warning only exists to keep code compilable as C++.  This project is
    # C-only, where implicit void*<->T* conversion is idiomatic (the calloc/
    # realloc idiom); it does NOT weaken -fbounds-safety's runtime size checks.
    ("implicit-void-ptr-cast", "C-only project; idiomatic void* conversion"),
]

CWARN = "-Werror -Weverything " + " ".join(
    "-Wno-" + name for name, _why in CWARN_DISABLED
)

CINC = "-Iinclude -Isrc"
OBJCWARN = "-Wall -Wextra"
FRAMEWORKS = "-framework Metal -framework Foundation"

# variant -> (opt flags, bounds-safety?, build tests?, build bench?)
VARIANTS = {
    "release": ("-Os", True, True, True),
    "debug": ("-O0 -g -fsanitize=address,integer,undefined -fno-sanitize-recover=all",
              True, True, False),
    "unsafe": ("-Os", False, False, True),
}


def obj(variant, src):
    return os.path.join("build", variant, "obj",
                        os.path.splitext(os.path.basename(src))[0] + ".o")


def main():
    core_c = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "src", "*.c")))
    shim_m = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "src", "*.m")))
    tests = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "tests", "test_*.c")))
    benches = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "bench", "*.c")))

    n = []
    w = n.append

    w("# Generated by configure.py -- do not edit by hand.")
    w("ninja_required_version = 1.10")
    w("")
    w(f"cstd = {CSTD}")
    w(f"cwarn = {CWARN}")
    w(f"cinc = {CINC}")
    w(f"objcwarn = {OBJCWARN}")
    w(f"frameworks = {FRAMEWORKS}")
    w("")
    w("# Rationale for each disabled warning:")
    for name, why in CWARN_DISABLED:
        w(f"#   -Wno-{name}: {why}")
    w("")

    for variant, (opt, bounds, _tests, _bench) in VARIANTS.items():
        bflag = (BOUNDS + " ") if bounds else ""
        w(f"rule cc_{variant}")
        w(f"  command = clang $cstd {bflag}$cwarn $cinc {opt} -MMD -MF $out.d -c $in -o $out")
        w("  depfile = $out.d")
        w("  deps = gcc")
        w(f"  description = CC({variant}) $out")
        w("")
        w(f"rule objc_{variant}")
        w(f"  command = clang $cstd -fobjc-arc $objcwarn $cinc --embed-dir=shaders {opt} -MMD -MF $out.d -c $in -o $out")
        w("  depfile = $out.d")
        w("  deps = gcc")
        w(f"  description = OBJC({variant}) $out")
        w("")
        w(f"rule link_{variant}")
        w(f"  command = clang {opt} $in $frameworks -o $out")
        w(f"  description = LINK({variant}) $out")
        w("")

    w("rule run")
    w("  command = $bin && touch $out")
    w("  description = TEST $bin")
    w("")
    w("rule benchcmp")
    w("  command = $cmd")
    w("  pool = console")
    w("  description = benchmark: cost of -fbounds-safety (per phase + e2e)")
    w("")

    # Bench stems, e2e "bench" sorted last; variants that build benches.
    bench_stems = sorted((os.path.splitext(os.path.basename(b))[0] for b in benches),
                         key=lambda s: (s == "bench", s))
    bench_variants = [v for v, cfg in VARIANTS.items() if cfg[3]]

    test_stamps = []
    for variant, (_opt, _bounds, do_tests, do_bench) in VARIANTS.items():
        lib_objs = []
        for c in core_c:
            o = obj(variant, c)
            w(f"build {o}: cc_{variant} {c}")
            lib_objs.append(o)
        for m in shim_m:
            o = obj(variant, m)
            w(f"build {o}: objc_{variant} {m}")
            lib_objs.append(o)
        w("")

        produced = []
        if do_tests:
            for t in tests:
                stem = os.path.splitext(os.path.basename(t))[0]
                o = obj(variant, t)
                exe = os.path.join("build", variant, stem)
                stamp = exe + ".runok"
                w(f"build {o}: cc_{variant} {t}")
                w(f"build {exe}: link_{variant} {o} {' '.join(lib_objs)}")
                w(f"build {stamp}: run {exe}")
                w(f"  bin = {exe}")
                produced.append(exe)
                test_stamps.append(stamp)
        if do_bench:
            for b in benches:
                stem = os.path.splitext(os.path.basename(b))[0]
                o = obj(variant, b)
                exe = os.path.join("build", variant, stem)
                w(f"build {o}: cc_{variant} {b}")
                w(f"build {exe}: link_{variant} {o} {' '.join(lib_objs)}")
                produced.append(exe)
        w("")
        w(f"build {variant}: phony {' '.join(produced)}")
        w("")

    # All bench executables (every stem in every bench-building variant).
    bench_exes = [f"build/{v}/{s}" for v in bench_variants for s in bench_stems]

    # One hyperfine invocation per phase, comparing the variants side by side, so
    # a slow phase can't mask a regression in a fast one.
    calls = []
    for s in bench_stems:
        args = " ".join(f'-n "{s} {v}" ./build/{v}/{s}' for v in bench_variants)
        calls.append(f"hyperfine --warmup 3 -N {args}")
    benchcmp_cmd = " ; ".join(calls)

    w(f"build test: phony {' '.join(test_stamps)}")
    w(f"build bench: phony {' '.join(bench_exes)}")
    # `benchcmp` names a file that is never created, so ninja always reruns it
    # (after building the binaries it depends on).
    w(f"build benchcmp: benchcmp {' '.join(bench_exes)}")
    w(f"  cmd = {benchcmp_cmd}")
    w("build all: phony release debug")
    w("default all")
    w("")

    with open(os.path.join(HERE, "build.ninja"), "w") as f:
        f.write("\n".join(n))
    print(f"wrote build.ninja: {len(core_c)} core .c, {len(shim_m)} shim .m, "
          f"{len(tests)} test(s), {len(benches)} bench(es)")


if __name__ == "__main__":
    main()
