#!/usr/bin/env python3
"""Generate build.ninja for the canvas2d project.

Two variants are produced from one source tree:

  release : -Os                         (optimized; the perf story)
  debug   : -O0 -g -fsanitize=...        (address,integer,undefined; the safety story)

The C core is compiled with -std=c23 -fbounds-safety -Werror -Weverything.  Only
the handful of warnings below are disabled, each for a concrete reason; everything
else in -Weverything stays on (that strictness is the whole point of the project).

The Objective-C Metal shim (src/*.m) is the boundary to a system framework, so it is
NOT compiled with -fbounds-safety/-Weverything -- just -Wall -Wextra.  It is still
built under the sanitizers in the debug variant.

The Metal shader is embedded with C23 #embed (the shim is built with -std=c23 and
--embed-dir=shaders) and compiled at runtime, so the build needs no offline Metal
toolchain component.  #embed dependencies are tracked automatically via -MMD.
"""

import os
import glob

HERE = os.path.dirname(os.path.abspath(__file__))


def rel(p):
    return os.path.relpath(p, HERE)


# --- flag groups -----------------------------------------------------------

CSTD = "-std=c23 -fbounds-safety"

# Disabled warnings.  Keep this list short and justified.
CWARN_DISABLED = [
    # /usr/local/include sits on clang's default search path on this machine;
    # this is a cross-compilation hygiene warning, irrelevant to a native build.
    ("poison-system-directories", "spurious for a native (non-cross) build"),
    # We declare __counted_by locals at their point of use; C89-style
    # "declare everything up top" is antithetical to modern C23.
    ("declaration-after-statement", "we use C23 declare-at-use style"),
    # Struct tail padding is not a correctness signal for this code.
    ("padded", "padding is not a correctness concern here"),
    # We target C23; warning that C23 features are 'incompatible with older C'
    # is backwards for this project.
    ("pre-c23-compat", "we deliberately target C23"),
    # This warning only exists to keep code compilable as C++.  This project is
    # C-only, where implicit void*<->T* conversion is idiomatic (the calloc/
    # realloc idiom); it does NOT weaken -fbounds-safety's runtime size checks
    # (an undersized allocation still traps).
    ("implicit-void-ptr-cast", "C-only project; idiomatic void* conversion"),
]

CWARN = "-Werror -Weverything " + " ".join(
    "-Wno-" + name for name, _why in CWARN_DISABLED
)

CINC = "-Iinclude -Isrc"
OBJCWARN = "-Wall -Wextra"
FRAMEWORKS = "-framework Metal -framework Foundation"

REL_OPT = "-Os"
DBG_OPT = "-O0 -g -fsanitize=address,integer,undefined -fno-sanitize-recover=all"

VARIANTS = {
    "release": REL_OPT,
    "debug": DBG_OPT,
}


def main():
    core_c = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "src", "*.c")))
    shim_m = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "src", "*.m")))
    shaders = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "shaders", "*.metal")))
    tests = sorted(rel(p) for p in glob.glob(os.path.join(HERE, "tests", "test_*.c")))

    n = []
    w = n.append

    w("# Generated by configure.py -- do not edit by hand.")
    w("ninja_required_version = 1.10")
    w("")
    w(f"cstd = {CSTD}")
    w(f"cwarn = {CWARN}")
    w(f"cinc = {CINC}")
    w(f"objcwarn = {OBJCWARN}")
    w(f"frameworks = {FRAMEWORKS}")
    w("")
    w("# Rationale for each disabled warning:")
    for name, why in CWARN_DISABLED:
        w(f"#   -Wno-{name}: {why}")
    w("")

    # Per-variant compile/link rules.
    for variant, opt in VARIANTS.items():
        w(f"rule cc_{variant}")
        w(f"  command = clang $cstd $cwarn $cinc {opt} -MMD -MF $out.d -c $in -o $out")
        w("  depfile = $out.d")
        w("  deps = gcc")
        w(f"  description = CC({variant}) $out")
        w("")
        w(f"rule objc_{variant}")
        w(f"  command = clang -std=c23 -fobjc-arc $objcwarn $cinc --embed-dir=shaders {opt} -MMD -MF $out.d -c $in -o $out")
        w("  depfile = $out.d")
        w("  deps = gcc")
        w(f"  description = OBJC({variant}) $out")
        w("")
        w(f"rule link_{variant}")
        w(f"  command = clang {opt} $in $frameworks -o $out")
        w(f"  description = LINK({variant}) $out")
        w("")

    w("rule run")
    w("  command = $bin && touch $out")
    w("  description = TEST $bin")
    w("")

    # Per-variant objects + test executables.
    variant_exes = {}
    for variant in VARIANTS:
        objdir = os.path.join("build", variant, "obj")
        lib_objs = []
        for c in core_c:
            o = os.path.join(objdir, os.path.splitext(os.path.basename(c))[0] + ".o")
            w(f"build {o}: cc_{variant} {c}")
            lib_objs.append(o)
        for m in shim_m:
            o = os.path.join(objdir, os.path.splitext(os.path.basename(m))[0] + ".o")
            w(f"build {o}: objc_{variant} {m}")
            lib_objs.append(o)
        w("")

        exes = []
        for t in tests:
            stem = os.path.splitext(os.path.basename(t))[0]
            o = os.path.join(objdir, stem + ".o")
            exe = os.path.join("build", variant, stem)
            w(f"build {o}: cc_{variant} {t}")
            w(f"build {exe}: link_{variant} {o} {' '.join(lib_objs)}")
            exes.append(exe)
        w("")
        variant_exes[variant] = exes
        w(f"build {variant}: phony {' '.join(exes)}")
        w("")

    # `test` runs every executable in both variants.
    stamps = []
    for variant, exes in variant_exes.items():
        for exe in exes:
            stamp = exe + ".runok"
            w(f"build {stamp}: run {exe}")
            w(f"  bin = {exe}")
            stamps.append(stamp)
    w("")
    w(f"build test: phony {' '.join(stamps)}")
    w("build all: phony release debug")
    w("default all")
    w("")

    with open(os.path.join(HERE, "build.ninja"), "w") as f:
        f.write("\n".join(n))
    print(f"wrote build.ninja: {len(core_c)} core .c, {len(shim_m)} shim .m, "
          f"{len(shaders)} shader(s), {len(tests)} test(s)")


if __name__ == "__main__":
    main()
