// Differential oracle against the SYSTEM zlib (-lz, the library macOS ships):
// hybrid H5 of docs/decisions/codec-outsourcing.md, adopted by its section 4.
// test_zlib.c's fixtures were generated by reference zlib once, by hand, during
// development; this test runs that cross-check live, both directions, forever:
//
//   (a) our deflate -> reference uncompress: our streams are spec-valid zlib
//       that the ecosystem's decoder reproduces byte-identically, not just
//       streams our own inflate happens to take back;
//   (b) reference compress2 at levels 0/1/6/9 (stored, fast, default, max --
//       level 9 emits dynamic-Huffman blocks) -> our inflate: our decoder
//       handles real-world encoder output across every block type;
//   (c) corrupted streams: both decoders see the same truncations and bit
//       flips at the same output cap and must agree -- reject for reject, and
//       identical bytes wherever both accept.
//
// The one place the verdicts legitimately differ is trailing garbage: the
// reference stops at stream end and calls leftover input success, while our
// strict end state (exactly four adler bytes may remain) rejects the buffer.
// Ours is the stricter-than-spec-minimum side, so the asymmetry runs one way
// only -- nothing the reference rejects may ever pass ours -- and the delta is
// pinned as its own test below, not silently allowed.
//
// Reference zlib is a TEST-ONLY dependency: this binary (and the fuzz_zlib_diff
// harness) gets -lz on its own link edge (configure.py's EXTRA_LIBS); no
// canvas library object in any variant links it.

#include "canvas2d_zlib.h"
#include "test_util.h"

#include <stdlib.h>
#include <string.h>
#include <zlib.h>

// Four encoder personalities: level 0 emits stored blocks, 1 trades ratio for
// speed, 6 is the ecosystem default, and 9 spends the most effort -- on
// repetitive text it emits the dynamic-Huffman blocks our own encoder never
// writes, so (b) exercises decode paths (a) cannot reach.
static int const ref_levels[4] = { 0, 1, 6, 9 };

// Deterministic bytes for the incompressible case (no rand(): same on every
// run).  xorshift32 in the house spelling: run in 64-bit and masked so the
// deliberate wrap stays out of -fsanitize=integer's lane (test_zlib pattern).
static uint32_t g_rng = 0x2545F491u;
static uint8_t rnd8(void) {
    uint64_t x = g_rng;
    x = (x ^ (x << 13)) & 0xFFFFFFFFu;
    x = x ^ (x >> 17);
    x = (x ^ (x << 5)) & 0xFFFFFFFFu;
    g_rng = (uint32_t)x;
    return (uint8_t)(x & 0xFFu);
}

static char const pangram[] =
    "the quick brown fox jumps over the lazy dog. "
    "pack my box with five dozen liquor jugs. "
    "how vexingly quick daft zebras jump! ";

// Reference inflate via uncompress2, which reports how many input bytes it
// consumed: it stops at stream end and treats leftovers as success, so
// *consumed < n is how trailing garbage reads back.  Returns the payload
// length, or -1 when the reference rejects.
static int ref_inflate(uint8_t *__counted_by(dcap) dst, int dcap,
                       uint8_t const *__counted_by(n) src, int n,
                       int *__single consumed) {
    uLongf dlen = (uLongf)dcap;
    uLong slen = (uLong)n;
    int const rc = uncompress2(dst, &dlen, src, &slen);
    *consumed = (int)slen;
    return rc == Z_OK ? (int)dlen : -1;
}

// (a) Our deflate must be real zlib: the reference decoder reproduces the
// input from our stream and consumes every byte of it (no slack emission).
static void ours_to_ref(uint8_t const *__counted_by(n) src, int n) {
    int const zcap = canvas2d_zlib_bound(n);
    int const pcap = n > 0 ? n : 1;
    uint8_t *__counted_by_or_null(zcap) z = malloc((size_t)zcap);
    uint8_t *__counted_by_or_null(pcap) back = malloc((size_t)pcap);
    CHECK(z != NULL && back != NULL);
    if (z && back) {
        int const zn = canvas2d_zlib_deflate(z, zcap, src, n);
        CHECK(zn > 0);
        if (zn > 0) {
            int consumed = 0;
            CHECK(ref_inflate(back, n, z, zn, &consumed) == n);
            CHECK(consumed == zn);
            CHECK(n == 0 || memcmp(back, src, (size_t)n) == 0);
        }
    }
    free(back);
    free(z);
}

// (b) The reference encoder's output at every level must inflate through ours
// to the exact input -- against an exact-size dst, so an overrun would trap.
static void ref_to_ours(uint8_t const *__counted_by(n) src, int n) {
    int const zcap = (int)compressBound((uLong)n);
    int const pcap = n > 0 ? n : 1;
    uint8_t *__counted_by_or_null(zcap) z = malloc((size_t)zcap);
    uint8_t *__counted_by_or_null(pcap) back = malloc((size_t)pcap);
    CHECK(z != NULL && back != NULL);
    if (z && back) {
        for (int l = 0; l < (int)(sizeof ref_levels / sizeof ref_levels[0]); l++) {
            uLongf zlen = (uLongf)zcap;
            CHECK(compress2(z, &zlen, src, (uLong)n, ref_levels[l]) == Z_OK);
            CHECK(canvas2d_zlib_inflate(back, n, z, (int)zlen) == n);
            CHECK(n == 0 || memcmp(back, src, (size_t)n) == 0);
        }
    }
    free(back);
    free(z);
}

static void both_ways(uint8_t const *__counted_by(n) src, int n) {
    ours_to_ref(src, n);
    ref_to_ours(src, n);
}

// (c) Verdict agreement on one (possibly corrupted) stream: both decoders eat
// the same bytes at the same output cap.  Reject must match reject; a stream
// both accept must produce identical bytes; and a reference accept that left
// input unconsumed is the trailing-garbage delta -- ours must reject the whole
// buffer but accept the exact prefix the reference consumed, byte-identically.
static void agree(uint8_t const *__counted_by(zn) zs, int zn, int pcap,
                  uint8_t *__counted_by(pcap) ours, uint8_t *__counted_by(pcap) refs) {
    int consumed = 0;
    int const r = ref_inflate(refs, pcap, zs, zn, &consumed);
    int o = canvas2d_zlib_inflate(ours, pcap, zs, zn);
    if (r < 0) {
        CHECK(o == -1);  // ours never accepts what the reference rejects
        return;
    }
    if (consumed < zn) {
        CHECK(o == -1);  // the documented strictness delta, one way only
        o = canvas2d_zlib_inflate(ours, pcap, zs, consumed);
    }
    CHECK(o == r);
    CHECK(r == 0 || memcmp(ours, refs, (size_t)r) == 0);
}

// Corrupt one valid stream every way this harness knows: truncate at every 8th
// length (and one byte short), then flip bits -- every bit when the stream is
// small enough to afford it, else a header / quarter-points / adler spread.
// Each corruption goes through agree(), not a blanket must-reject: a flip in
// a padding bit can leave the stream valid, and then both sides must accept it
// identically.
static void corruptions(uint8_t const *__counted_by(zn) zs, int zn, int pcap) {
    int const ocap = pcap;  // locals: a local pointer's bound can't name a parameter
    int const gcap = zn;
    uint8_t *__counted_by_or_null(ocap) ours = malloc((size_t)ocap);
    uint8_t *__counted_by_or_null(ocap) refs = malloc((size_t)ocap);
    uint8_t *__counted_by_or_null(gcap) g = malloc((size_t)gcap);
    CHECK(ours != NULL && refs != NULL && g != NULL);
    if (ours && refs && g) {
        for (int k = 0; k < zn; k += 8) {
            agree(zs, k, pcap, ours, refs);
        }
        agree(zs, zn - 1, pcap, ours, refs);
        memcpy(g, zs, (size_t)zn);
        if (zn <= 4096) {
            for (int byte = 0; byte < zn; byte++) {
                for (int bit = 0; bit < 8; bit++) {
                    g[byte] ^= (uint8_t)(1u << bit);
                    agree(g, zn, pcap, ours, refs);
                    g[byte] ^= (uint8_t)(1u << bit);
                }
            }
        } else {
            int const spots[] = { 0,      1,      2,      3,      zn / 4, zn / 2,
                                  3 * (zn / 4),   zn - 4, zn - 3, zn - 2, zn - 1 };
            for (int s = 0; s < (int)(sizeof spots / sizeof spots[0]); s++) {
                for (int bit = 0; bit < 8; bit++) {
                    g[spots[s]] ^= (uint8_t)(1u << bit);
                    agree(g, zn, pcap, ours, refs);
                    g[spots[s]] ^= (uint8_t)(1u << bit);
                }
            }
        }
    }
    free(g);
    free(refs);
    free(ours);
}

// ---- the tests --------------------------------------------------------------

// The round-trip corpus, test_zlib's shapes: empty, one byte, long runs
// (overlapping dist-1 copies), the dist-2 classic, repetitive text crossing
// 64K at an odd length, incompressible bytes, an emoji-capture-like RGBA disc,
// and lengths bracketing the 16-bit boundaries.
static void test_corpus(void) {
    uint8_t one = 0x42;
    both_ways(&one, 0);
    both_ways(&one, 1);

    enum { big = 200001, zeros = 100000, ab = 80000, rnd = 70001, rgba = 160 * 160 * 4 };
    int const cap = big;
    uint8_t *__counted_by_or_null(cap) buf = malloc((size_t)cap);
    CHECK(buf != NULL);
    if (!buf) {
        return;
    }

    memset(buf, 0, zeros);  // long runs -> overlapping dist-1 copies
    both_ways(buf, zeros);

    for (int i = 0; i < ab; i++) {  // dist-2 overlap, the classic
        buf[i] = (uint8_t)((i & 1) ? 'b' : 'a');
    }
    both_ways(buf, ab);

    for (int i = 0; i < big; i++) {  // text, crossing 64K, odd length
        buf[i] = (uint8_t)pangram[i % (int)(sizeof pangram - 1)];
    }
    both_ways(buf, big);

    for (int i = 0; i < rnd; i++) {  // incompressible
        buf[i] = rnd8();
    }
    both_ways(buf, rnd);

    for (int y = 0; y < 160; y++) {  // emoji-capture-like RGBA: mostly
        for (int x = 0; x < 160; x++) {  // transparent, a gradient disc of ink
            int const o = (y * 160 + x) * 4;
            if ((x - 80) * (x - 80) + (y - 80) * (y - 80) < 60 * 60) {
                buf[o + 0] = (uint8_t)x;
                buf[o + 1] = (uint8_t)y;
                buf[o + 2] = (uint8_t)((x + y) / 2);
                buf[o + 3] = 255;
            } else {
                buf[o + 0] = buf[o + 1] = buf[o + 2] = buf[o + 3] = 0;
            }
        }
    }
    both_ways(buf, rgba);

    for (int i = 0; i < cap; i++) {  // lengths bracketing the 16-bit boundaries
        buf[i] = (uint8_t)((i % 251) ^ (i >> 6));
    }
    static int const sizes[] = { 2, 3, 255, 256, 257, 65534, 65535, 65536, 65537 };
    for (int s = 0; s < (int)(sizeof sizes / sizeof sizes[0]); s++) {
        both_ways(buf, sizes[s]);
    }

    free(buf);
}

// Corruption agreement over all three block types plus our own emission:
// level 0 (stored), 6 and 9 (fixed/dynamic mixes; 9 on this text is dynamic),
// and our deflate's fixed-Huffman stream, each truncated and bit-flipped.
static void test_corruption_agreement(void) {
    enum { pn = 20001, pcap = pn + 8 };
    int const zcap = canvas2d_zlib_bound(pn);  // > compressBound(pn): fits both encoders
    uint8_t *__counted_by_or_null(pn) plain = malloc((size_t)pn);
    uint8_t *__counted_by_or_null(zcap) z = malloc((size_t)zcap);
    CHECK(plain != NULL && z != NULL);
    if (plain && z) {
        CHECK(zcap >= (int)compressBound((uLong)pn));
        for (int i = 0; i < pn; i++) {
            plain[i] = (uint8_t)pangram[i % (int)(sizeof pangram - 1)];
        }
        static int const levels[] = { 0, 6, 9 };
        for (int l = 0; l < (int)(sizeof levels / sizeof levels[0]); l++) {
            uLongf zlen = (uLongf)zcap;
            CHECK(compress2(z, &zlen, plain, (uLong)pn, levels[l]) == Z_OK);
            corruptions(z, (int)zlen, pcap);
        }
        int const zn = canvas2d_zlib_deflate(z, zcap, plain, pn);
        CHECK(zn > 0);
        if (zn > 0) {
            corruptions(z, zn, pcap);
        }
    }
    free(z);
    free(plain);
}

// The strictness delta, pinned so a behavior change on either side fails here
// (and gets re-litigated) instead of drifting silently: a valid stream with
// garbage appended.  The reference accepts the buffer -- uncompress stops at
// stream end, consuming exactly the stream -- while ours rejects it outright,
// then accepts the consumed prefix.  This is the only known accept-set
// difference between the two decoders, and it runs in the safe direction.
static void test_trailing_garbage_delta(void) {
    uint8_t const plain[8] = { 'c', 'a', 'n', 'v', 'a', 's', '2', 'd' };
    uint8_t z[64];
    int const zn = canvas2d_zlib_deflate(z, 60, plain, (int)sizeof plain);
    CHECK(zn > 0 && zn <= 60);
    if (zn <= 0 || zn > 60) {
        return;
    }
    uint8_t out[16];
    static uint8_t const junk[] = { 0x00, 0xAA, 0x78 };  // incl. a header-looking byte
    for (int extra = 1; extra <= (int)(sizeof junk / sizeof junk[0]); extra++) {
        for (int j = 0; j < extra; j++) {
            z[zn + j] = junk[j];
        }
        int consumed = 0;
        CHECK(ref_inflate(out, (int)sizeof out, z, zn + extra, &consumed) == 8);
        CHECK(consumed == zn);  // the reference stopped at stream end...
        CHECK(memcmp(out, plain, sizeof plain) == 0);
        CHECK(canvas2d_zlib_inflate(out, (int)sizeof out, z, zn + extra) == -1);  // ...ours refuses
        CHECK(canvas2d_zlib_inflate(out, (int)sizeof out, z, zn) == 8);  // the bare stream is fine
        CHECK(memcmp(out, plain, sizeof plain) == 0);
    }
}

int main(void) {
    test_corpus();
    test_corruption_agreement();
    test_trailing_garbage_delta();
    return TEST_REPORT();
}
