#!/usr/bin/env python3
"""Format `llvm-cov export -summary-only` JSON (stdin) into a Markdown coverage
table (stdout) for docs/coverage.md -- a checked-in, GitHub-browsable report.

Deterministic on purpose: files are sorted by line coverage (least first) then
name, and nothing time-varying is emitted, so the committed report changes only
when coverage actually changes -- a `git diff` then shows exactly what moved.
Run via `ninja coverage`."""

import json
import sys


def pct(summary, key):
    return summary[key]["percent"]


def cell(summary, key):
    s = summary[key]
    return "—" if s["count"] == 0 else f"{s['percent']:.1f}%"


def main():
    data = json.load(sys.stdin)["data"][0]
    totals = data["totals"]

    # Skip files with no functions (pure-declaration headers) -- their 0/0 counts
    # report as a meaningless 0%.
    rows = [(f["filename"].rsplit("/", 1)[-1], f["summary"])
            for f in data["files"] if f["summary"]["functions"]["count"] > 0]
    rows.sort(key=lambda r: (pct(r[1], "lines"), r[0]))

    out = sys.stdout.write
    out("# Coverage\n\n")
    out("Source-based line/region/branch coverage of `src/` from the test suite "
        "(software backend, `-O0`).\n")
    out("Generated by `ninja coverage` -- do not edit by hand.  Sorted by line "
        "coverage, least-covered first.\n\n")
    out(f"**{pct(totals, 'lines'):.1f}% of {totals['lines']['count']} lines covered.**\n\n")
    out("| File | Lines | Functions | Regions | Branches |\n")
    out("|---|--:|--:|--:|--:|\n")
    for name, s in rows:
        out(f"| `{name}` | {cell(s, 'lines')} | {cell(s, 'functions')} "
            f"| {cell(s, 'regions')} | {cell(s, 'branches')} |\n")
    out(f"| **total** | **{cell(totals, 'lines')}** "
        f"| **{cell(totals, 'functions')}** | **{cell(totals, 'regions')}** "
        f"| **{cell(totals, 'branches')}** |\n")


if __name__ == "__main__":
    main()
